### ISSUE TITLE
USER STORY: Site User - Delete comments

### ISSUE THREAD

**Issue by KarlPreisler** [KarlPreisler/hiking-spots-blog#13]
As a **Site user** I can **Delete a comment** so that **I have the ability to change my mind about comments I made**

# Acceptance Criteria:
* Acceptance Criteria 1: When a comment is approved, the option to delete the comment is visible to the user.
* Acceptance Criteria 2: If the delete button is clicked, the comment should be erased and no longer be visible to any users. 

# Tasks
- [x] Create a URL for deleting comments 
- [x] Create CommentDeleteView class and link to URL
- [x] Add user interface to trigger functions using Post method
