### ISSUE TITLE
USER STORY: Site Admin - Adding posts

### ISSUE THREAD

**Issue by KarlPreisler** [KarlPreisler/hiking-spots-blog#14]
As a **Admin** I can **add posts through the dashboard** so that **I can add posts without having to access the admin panel**

# Acceptance Critera:
* Acceptance Critera 1: When logged in as admin, a button to Add a Post should be visible.
* Acceptance Critera 2: The button should take admin to a seperate URL.
* Acceptance Critera 3: The URL will contain a form with the same fields as those in the admin panel.
* Acceptance Critera 4: A button to Submit the blog post will be visible at the bottom of the form. 
* Acceptance Critera 5: The Submit button should have a post method, and redirect users to the Add Post page.
* Acceptance Critera 6: A message indicating that the post was succesfully submitted should display to the user.

# Tasks:
- [x] Create model for adding posts
- [x] Create class AddPost in views.py
- [x] Create add_post_form in forms.py
- [x] Create HTML file for adding posts
- [x] Create and link URL to new HTML file
- [x] Define absolute_url to reverse admin once blog post is published
- [x] Add success & error messages in views.py to display once the submit button is clicked
- [x] Add authentication so that Add Post button only appears to super users/admins.
