### ISSUE TITLE
USER STORY: Site User - About us Page

### ISSUE THREAD

**Issue by KarlPreisler** [KarlPreisler/hiking-spots-blog#17]
As a **Site user** I can **Read about the company in the "about us" section** so that **I can understand the story of the company**

# Acceptance Criteria: 
* Acceptance Criteria 1: In the left navigation bar, There is a link labelled "About" that is clickable.
* Acceptance Criteria 2: The link should take users to a different page with information about the company.
* Acceptance Criteria 3: 

# Tasks: 
- [ ] Create template html file for about page
- [ ] Create path in urls.py
- [ ] Create class in views.
