### ISSUE TITLE
USER STORY: Site User - Difficulty levels

### ISSUE THREAD

**Issue by KarlPreisler** [KarlPreisler/hiking-spots-blog#18]
As a **Site user** I can **view a page explaining how difficulty levels are calculated** so that **I can understand the different difficulty levels**

# Acceptance Criteria:
* Acceptance Criteria 1: When clicking on the left drop-down menu on the home page, a link labelled "Difficulty Levels" should appear
* Acceptance Criteria 2: The link should take users to a page that explains how the difficulty levels are calculated

# Tasks: 
- [ ] Add a template for the difficulty page
- [ ] Add URL 
- [ ] Add content for the difficulty page
- [ ] Add link in the navigation bar
