### ISSUE TITLE
USER STORY: Site User - Google Static Map

### ISSUE THREAD

**Issue by KarlPreisler** [KarlPreisler/hiking-spots-blog#19]
As a **Site user** I can **view an image of a map for an individual trail** so that **I can see where the trail is located**

# Acceptance Criteria:
* Acceptance Criteria 1: When viewing an indivual blog post, a map is rendered underneath the content.
* Acceptance Criteria 2: The map is a satellite image of the coordinates for the hiking trail.

# Tasks:
- [ ] Get API Credentials from the Google Cloud Platform and insert them into the settings file.
- [ ] Define latitude and longitude in models.py.
- [ ] Call coordinates in views.py to create the image.
- [ ] Add image location in Post_details.
- [ ] Add bootstrap classes to make image responsive.
