### ISSUE TITLE
USER STORY: Site User - Log in 

### ISSUE THREAD

**Issue by KarlPreisler** [KarlPreisler/hiking-spots-blog#20]
As a **user** I can **log in to an already existing account** so that **I can post comments and like posts.** 

# Acceptance Critera:
* Acceptance Critera 1: The ability to log in should be a link in the right navigation bar.
* Acceptance Critera 2: Clicking on Log in will open a log in window where users can fill in their credentials.
* Acceptance Critera 3: If the credentials are false, user will be notified.
* Acceptance Critera 4: If the credentials are correct, redirect users to the home page 
* Acceptance Critera 5: Include a success message indicating that the user logged in successfully.

# Tasks
- [ ] Add login path in urls.py.
- [ ] Add template for the log in page
- [ ] Add success message for 3 seconds with the text "Successfully logged in as "{name}"
