### ISSUE TITLE
USER STORY: Site User - Logout

### ISSUE THREAD

**Issue by KarlPreisler** [KarlPreisler/hiking-spots-blog#21]
As a **Site user/admin** I can **log out of my account** so that **I am no longer logged in**

# Acceptance Criteria:
* Acceptance Criteria 1: The option to logout should appear in right dropdown menu in the navigation bar when user is logged in. 
* Acceptance Criteria 2: Users clicking the logout button should be redirected to a page where users can confirm the logout or go back to the previous site. 
* Acceptance Criteria 3: A success message should be visible for 3 seconds after logging out to indicate that the user was successfully signed out. 

# Tasks
- [ ] Add path to logout page in urls.py
- [ ] Create a template following base.html for the logout page. 
- [ ] Add success message that appears for 3 seconds.
